cache:
  event: ["~/.m2"]

shared:
  annotations:
    screwdriver.cd/cpu: TURBO
    screwdriver.cd/ram: TURBO
  image: maven:3.6.3-jdk-8

jobs:
  pull-commit:
    requires: [~pr]
    steps:
      - header: echo "Starting the pipeline"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2
      - install: >
        mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install
        -Pcoverage.build
      - site: >
          mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn post-site
            -Pcoverage.report,sonar
      - sonar: >
          mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn sonar:sonar
              -Dsonar.projectKey=yahoo_fili -Dsonar.organization=yahoo -Dsonar.login=${SONAR_TOKEN}
              -Pcoverage.report,sonar
          || true

  master-commit:
    requires: [~commit:sd-master, ~commit:master]
    steps:
      - header: echo "Starting the pipeline"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2
      - install: >
        mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install
            -Pcoverage.build
      - site: >
          mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn post-site
            -Pcoverage.report,sonar
      - sonar: >
          mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn sonar:sonar
              -Dsonar.projectKey=yahoo_fili -Dsonar.organization=yahoo -Dsonar.login=${SONAR_TOKEN}
              -Pcoverage.report,sonar
          || true
      - release: ./screwdriver/is_whitelisted.bash && ./screwdriver/tag-for-release.bash

  tag-release:
    secrets:
      - BINTRAY_USER
      - BINTRAY_API_KEY
    requires: [~tag:/^\d+\.\d+\.\d+$/]
    steps:
      - header: echo "Starting the pipeline"
      - lua-install: apt-get update -qy && apt-get install -y lua5.2 idea
      - release: ./screwdriver/is_whitelisted.bash && ./screwdriver/bintray-publish.bash
